# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=irc/server/config
GOFILES=\
	config.go\
	port.go\
	oper.go\
	link.go\
	ban.go\
	info.go\
    settings.go\

include $(GOROOT)/src/Make.pkg
